// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHeTsBWyNu3d04xD2gCyZi_evDXbaL6Hw',
    appId: '1:726218311510:web:e4d4028c60d6a1856938f7',
    messagingSenderId: '726218311510',
    projectId: 'bravo-challenge',
    authDomain: 'bravo-challenge.firebaseapp.com',
    storageBucket: 'bravo-challenge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdFzT_A4Ey6pnrPB_0qg_4TygYqJVJTn4',
    appId: '1:726218311510:android:ba4324bffbaaaff06938f7',
    messagingSenderId: '726218311510',
    projectId: 'bravo-challenge',
    storageBucket: 'bravo-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK0_N89XGk9eAS8QruzFVNhVx-kjoghjE',
    appId: '1:726218311510:ios:2d314de64955dc7a6938f7',
    messagingSenderId: '726218311510',
    projectId: 'bravo-challenge',
    storageBucket: 'bravo-challenge.appspot.com',
    iosBundleId: 'com.example.bravoChallenge',
  );
}
